modules/contrib/opigno_social/modules/opigno_social_community/src/Form/CommunityDeleteForm.php
<?php

namespace Drupal\opigno_social_community\Form;

use Drupal\Core\Entity\ContentEntityDeleteForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Defines the Opigno community delete form.
 *
 * @package Drupal\opigno_social_community\Form
 */
class CommunityDeleteForm extends ContentEntityDeleteForm {

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return $this->t('Do you want delete the community?');
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->t('You are going to delete the community and all the messages linked to it. <strong>This action is not reversible.</strong>');
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Yes, delete the community');
  }

  /**
   * {@inheritdoc}
   */
  protected function actionsElement(array $form, FormStateInterface $form_state) {
    $actions = parent::actionsElement($form, $form_state);
    $actions['cancel']['#weight'] = 0;

    // Override links if the form has been rendered with ajax.
    if (!$form_state->get('ajax_modal')) {
      return $actions;
    }

    $actions['cancel']['#url'] = Url::fromRoute('<none>');
    $actions['cancel']['#attributes']['class'] += [
      'close',
      'btn',
      'btn-rounded',
    ];
    $actions['cancel']['#attributes']['data-dismiss'] = 'modal';

    return $actions;
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state);

    // Redirect to the different pages depending on the AJAX.
    $redirect_url = $form_state->get('ajax_modal')
      ? Url::fromRoute('opigno_social_community.join_communities')
      : Url::fromRoute('view.communities.collection');
    $form_state->setRedirectUrl($redirect_url);
  }

}

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-communities-join-page.html.twig
{#
/**
 * @file
 * Default theme implementation for the "Join communities" page.
 */
#}

<div class="join-communities-page-title block-page-title-block">
  <h1>{{ 'Join communities'|t }}</h1>
  {{ create_btn }}
</div>

<div class="communities-listing-wrapper row">
  <div class="col-left col-xxl-5 col-lg-6 col-md-12">
    {{ listing }}
  </div>

  <div class="col-right col-xxl-4 col-lg-5 col-md-12">
    <div class="content-box">
      {{ pending }}
    </div>
  </div>
</div>

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-available-communities.html.twig
{#
/**
 * @file
 * Default theme implementation for the uses's available communitites list.
 */
#}

{{ join_btn }}

<div class="content-box">
  <h3 class="content-box__title">
    {{ 'Your communities'|t }}

    <i class="fi fi-rr-angle-down d-xl-none"></i>
  </h3>

  <div class="communities-list">
    {% if managed %}
      <h5>{{ 'Communities you manage'|t }}</h5>
      {% for community in managed %}
        {{ community }}
      {% endfor %}
    {% endif %}

    {% if followed %}
      <h5>{{ 'Communities you follow'|t }}</h5>
      {% for community in followed %}
        {{ community }}
      {% endfor %}
    {% endif %}
  </div>
</div>

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-invitation.html.twig
{#
/**
 * @file
 * Default theme implementation for the Opigno community invitation entity.
 *
 * @ingroup themeable
 */
#}

{{ invited_user }}

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-leave-confirmation.html.twig
{#
/**
 * @file
 * Default theme implementation to display the "Leave community" confirmation.
 */
#}

{% if confirm_url %}
  <div class="modal modal-ajax community-modal-actions fade" tabindex="-1" role="dialog" aria-label="{{ title }}">
    <div class="modal-dialog modal-dialog-centered community-modal" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title">{{ 'Do you want leave the community?'|t }}</h2>
        </div>

        <div class="modal-body">
          <p>
            {{ 'You are going to leave the community, but your messages stay.'|t }}
            <br>
            <strong>{{ 'This action is not reversible.'|t }}</strong>
          </p>
          <p>
            <i>{{ 'If the community is private, you must receive an invitation again to access it.'|t }}</i>
          </p>
          <div class="actions">
            <a class="btn btn-rounded" type="button" aria-label="{{ 'Cancel'|t }}" data-dismiss="modal">{{ 'Cancel'|t }}</a>
            <a href="{{ confirm_url }}" class="btn btn-bg btn-rounded use-ajax">{{ 'Yes, leave the community'|t }}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-links-dropdown.html.twig
{#
/*
 * @file
 * Default theme implementation for the community member actions dropdown.
 *
 * Avalable variables:
 * - actions: the list of action links.
 */
#}

{% if links %}
  <div class="dropdown">
    <button class="comment-item__edit-btn dropdown-toggle" data-toggle="dropdown">
      <i class="fi fi-rr-menu-dots"></i>
    </button>

    <ul class="comment-item__edit-menu dropdown-menu dropdown-menu-right">
      {% for link in links %}
        <li class="dropdown-item">{{ link }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-manage-members-links-block.html.twig
{#
/**
 * @file
 * Default theme implementation to display the community members links block.
 */
#}

<div class="col-xxl-3 col-lg-4 col-md-12 aside-col">
  <div class="step-list-aside-wrapper content-box">
    <h3 class="content-box__title">{{ title }}</h3>
    <ul class="list-unstyled step-list-aside">
      {% for link in links %}
        {% if link.active %}
          <li class="active">{{ link.link }}</li>
        {% else %}
          <li>{{ link.link }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-modal.html.twig
{#
/**
 * @file
 * Default theme implementation to display the Opigno community modal window.
 *
 * Available varaibles:
 * - title: the popup title;
 * - body: the popup body;
 * - classes: the extra wrapper classes.
 */
#}

<div class="modal modal-ajax {{ classes|join(' ') }} fade" tabindex="-1" role="dialog" aria-label="{{ title }}">
  <div class="modal-dialog modal-dialog-centered community-modal" role="document">
    <div class="modal-content">
      <div class="modal-header">
        {% if title is not empty %}
          <h2 class="modal-title">{{ title }}</h2>
        {% endif %}
        <a href="" class="close close-x use-ajax" type="button" aria-label="{{ 'Close'|t }}" data-dismiss="modal">
          <i class="fi fi-rr-cross-small"></i>
        </a>
      </div>

      <div class="modal-body">{{ body }}</div>
    </div>
  </div>
</div>

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-post.html.twig
{#
/**
 * @file
 * Default theme implementation to display Opigno post entity.
 *
 * Available varaibles:
 * - post: the full Opigno post entity;
 * - id: the post ID;
 * - author: the rendered author entity;
 * - author_link: the url of the author entity;
 * - author_name: the author displayed name;
 * - text: the post text;
 * - created: the post creation timestamp;
 * - add_comment_link: the link to trigger the "Create comment" form opening;
 * - comments: the block with the comment form and all post comments;
 * - is_pinned: if the post is pinned or not;
 * - is_last_viewed: if the post is the last one that was viewed by the user;
 * - like_link: the link to like/dislike the post;
 * - like_count_link: the link to display the list of people who liked the post;
 * - attachment: the post shared attachment (training/badge/certificate).
 */
#}

<div {{ attributes }}>
  {{ author }}
  {{ text }}
  {{ created|format_date('post_date') }}
</div>

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community-restricted-feed.html.twig
{#
/**
 * @file
 * Default theme implementation for the restricted community feed.
 */
#}

<div class="restricted-text">
  <h2 class="content-box__title">{{ 'This community is restricted.'|t }}</h2>
  <p>{{ 'The messages will be visible once your request to join has been approved'|t }}</p>
</div>

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-community.html.twig
{#
/**
 * @file
 * Default theme implementation for the Opigno community entity.
 *
 * @ingroup themeable
 */
#}

{{ content.title }}
{{ content.description }}

modules/contrib/opigno_social/modules/opigno_social_community/templates/opigno-connections-communities-block.html.twig
{#
/**
 * @file
 * Default theme implementation to display connections/communities block.
 */
#}

<div id="opigno-connections-communities-block" class="opigno-connections-communities-block content-box">
  <h2 class="content-box__title">{{ 'Social'|t }}</h2>
  <p class="connections-number">
    {% trans %}
      You have <strong>1</strong> connection
    {% plural connections %}
      You have <strong>{{ connections }}</strong> connections
    {% endtrans %}
  </p>
  {{ connections_link }}

  {% if communities %}
    <h5>{{ 'Your communities'|t }}</h5>
    {% for community in communities %}
      {{ community }}
    {% endfor %}
  {% endif %}

  <div class="see-connections">
    {{ communities_feed_link }}
  </div>
</div>